Repository l5yth/potato-mesh, pull requests merged in 2025-09, with the labels that each got.

#8 feat: load nodes from json for tests
  data/__init__.py
  data/nodes.py
  test/test.sh
  test/test_web_app.py
Labels: codex

#10 Ignore Python __pycache__ directories
  .gitignore
Labels: codex

#11 Add JSON ingest API for node updates
  data/nodes.py
  test/test_web_app.py
  web/app.rb
Labels: codex

#12 Remove raw node JSON column
  data/nodes.py
  data/nodes.sql
  test/test_nodes_serialization.py
  web/app.rb
Labels: codex

#16 Color markers by role with grayscale map
  web/public/nodes.html
Labels: codex

#17 Add chat box for node notifications
  web/public/nodes.html
Labels: codex

#18 Adjust marker size and map tile opacity
  web/public/nodes.html
Labels: codex

#19 Display position time in relative 'time ago' format
  web/public/nodes.html
Labels: codex

#20 Sort initial chat entries by last-heard
  web/public/index.html
Labels: codex

#22 Add persistent footer with contact information
  web/public/index.html
Labels: codex

#23 Add first_heard timestamp
  data/migrations/001_add_first_heard.sql
  data/nodes.py
  data/nodes.sql
  test/test_nodes_serialization.py
  web/app.rb
Labels: codex

#29 Add optional debug logging for node and message operations
  data/mesh.py
Labels: codex

#30 refactor: replace deprecated utcfromtimestamp
  data/mesh.py
Labels: codex

#31 Clamp node timestamps and sync last_heard with position time
  data/mesh.py
  web/app.rb
Labels: codex

#33 Add messages API endpoint with node details
  web/app.rb
Labels: codex

#35 Normalize future timestamps for nodes
  data/mesh.py
  web/app.rb
Labels: codex

#38 Sort chat entries by timestamp
  web/public/index.html
Labels: codex

#44 Display filtered active node counts in #MediumFast subheading
  web/public/index.html
Labels: codex

#45 Harden mesh utilities
  data/mesh.py
  data/mesh.sh
  web/app.rb
  web/app.sh
Labels: codex

#46 feat: make frontend responsive for mobile
  web/public/index.html
Labels: codex

#47 Add daily date separators to chat log
  web/public/index.html
Labels: codex

#49 Show daily node count in title and header
  web/public/index.html
Labels: codex

#56 Add message ingestion API and stricter auth
  README.md
  web/app.rb
Labels: codex

#59 Convert boolean flags for SQLite binding
  web/app.rb
Labels: codex

#63 Fix nested dataclass serialization for node snapshots
  CHANGELOG.md
  data/mesh.py
Labels: codex

#65 style: condense node table
  web/views/index.erb
Labels: codex

#67 Normalize message sender IDs using node numbers
  web/app.rb
Labels: codex

#74 create ruby workflow
  .github/workflows/ruby.yml
Labels: ci

#78 Add Codecov upload step to Ruby workflow
  .github/workflows/ruby.yml
Labels: codex

#81 Configure SimpleCov reporting for Codecov
  web/Gemfile
  web/spec/spec_helper.rb
Labels: codex

#86 Add coverage for debug logging on messages without sender
  web/app.rb
  web/spec/app_spec.rb
Labels: codex

#89 Add unit tests for mesh ingestor script
  tests/test_mesh.py
Labels: codex

#95 Add penetration tests for authentication and SQL injection
  web/spec/app_spec.rb
Labels: codex

#98 Fix message spec node lookup for numeric IDs
  web/spec/app_spec.rb
Labels: codex

#99 Handle missing node metadata when joining messages
  web/app.rb
Labels: codex

#102 Add long name tooltip to short name badge
  web/views/index.erb
Labels: codex

#103 Add site info overlay
  web/views/index.erb
Labels: codex

#104 Adjust Leaflet popup styling for dark mode
  web/views/index.erb
Labels: codex

#105 Add auto-refresh toggle to UI
  web/views/index.erb
Labels: codex

#108 Handle message updates based on sender info
  web/app.rb
  web/spec/app_spec.rb
Labels: codex

#114 Add client-side sorting to node table
  web/views/index.erb
Labels: codex

#117 Add PotatoMesh logo to header and favicon
  web/public/potatomesh-logo.svg
  web/views/index.erb
Labels: codex

#132 Fix dark mode tile styling on new map tiles
  web/views/index.erb
Labels: web, codex

#122 feat: Add comprehensive Docker support
  .dockerignore
  .env.example
  .github/workflows/README.md
  .github/workflows/docker.yml
  .gitignore
  CHANGELOG.md
  DOCKER.md
  README.md
  configure.sh
  data/Dockerfile
  data/requirements.txt
  docker-compose.dev.yml
  docker-compose.prod.yml
  docker-compose.yml
  web/Dockerfile
Labels: enhancement, ci

#135 fix: use supported ruby image
  web/Dockerfile
Labels: codex

#137 fix: restore alpine build tooling for ingestor
  data/Dockerfile
Labels: codex

#138 fix: retain alpine runtime libs after removing build deps
  data/Dockerfile
Labels: codex

#140 Add clickable role filters to the map legend
  web/views/index.erb
Labels: codex

#143 Support mock serial interface in CI
  .github/workflows/docker.yml
  data/mesh.py
  tests/test_mesh.py
Labels: codex

#145 Ensure sqlite3 builds from source on Alpine
  web/Dockerfile
Labels: codex

#146 Fix sqlite3 native extension on Alpine
  web/Dockerfile
Labels: codex

#149 Require time library before formatting ISO timestamps
  .env.example
  DOCKER.md
  README.md
  docker-compose.dev.yml
  docker-compose.prod.yml
  docker-compose.yml
  web/app.rb
Labels: codex

#181 Add placeholder nodes for unknown senders
  web/app.rb
  web/spec/app_spec.rb
Labels: codex

#185 Update last heard on node entry change
  web/app.rb
  web/spec/app_spec.rb
  web/views/index.erb
Labels: webapp

#186 Add connection recovery for TCP interface
  data/mesh.py
  tests/test_mesh.py
Labels: ingestor
